config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comment/create'

  get 'comments/index'

  get 'comments/show'

  get 'comments/create'

  get 'comments/new'

  get 'comments/update'

  get 'comments/edit'

  get 'comments/destroy'

  devise_for :users
  get 'docs/index'

  get 'welcome/index'

  root 'welcome#index'

  resources :docs do 
    resources :comments
  end

  namespace :api do
    resources :docs do
      resources :comments, only: [:create, :update, :destroy]
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :doc
end

app/models/doc.rb
class Doc < ActiveRecord::Base
	belongs_to :user
	belongs_to :welcome
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :docs
  has_many :welcomes
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
  belongs_to :user
  has_many :docs
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :find_comment

  def create
    comment = @doc.comments.new(comment_params)
    if item.save
      render status: 200, json: {
        message: "Successfully created To-do Item.",
        todo_list: @doc,
        todo_item: comment
      }.to_json
    else
      render status: 422, json: {
        message: "To-do Item creation failed.",
        errors: comment.errors
      }.to_json
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

  def find_comment
    @doc = Doc.find(params[:doc_id])
  end
end

app/controllers/api/docs_controller.rb
class Api::DocsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  
  def index
    render json: Doc.all
  end

  def show
  	doc = Doc.find(params[:id])
  	render json: doc
  end

  def create
  	doc = Doc.new(doc_params)
  	 if doc.save
      head 200
    else
      head 500
    end
  end

  def destroy
  	doc = Doc.find(params[:id])
  	doc.destroy
  	render json: {
  		status: 200,
  		message: "Successfully deleted!"
  	}.to_json
  end

  def update
  	doc = Doc.find(params[:id])
  	if doc.update
  		head 200
  	else
  		head 500
  	end
  end

  private
  def doc_params
  	params.require(:doc).permit(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@doc = Doc.find(params[:doc_id])
  	@comment = @doc.comments.create(params[:comment].permit(:comment))
  	redirect_to doc_path(@doc)
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  def index
  	@doc = Doc.where(user_id: current_user)
  end

  def new
  	@doc = current_user.docs.build
  end

  def create
  	@doc = current_user.docs.build(doc_params)
  	if @doc.save
  		redirect_to @doc
  	else
  		render 'new'
  	end
  end

  def edit
  	@doc = Doc.find(params[:id])
  end

  def update
  	@doc = Doc.find(params[:id])
  	if @doc.update(doc_params)
  		redirect_to @doc
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@doc = Doc.find(params[:id])
  	@doc.destroy
  	redirect_to docs_path
  end

  def show
  	@doc = Doc.find(params[:id])
  end

  private 
  	def doc_params
  		params.require(:doc).permit(:title, :content)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if user_signed_in? && Doc.count != 0
    	@doc = current_user.docs.last
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/comments/_comment.html.erb
<div class = "comment clearfix">
	<div class = "comment_content">
		<p class = "comment_body">
			<%= comment.comment %>
		</p>
		<p class = "comment_title">
			<%= time_ago_in_words(comment.created_at) %> ago
		</p>
	</div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@doc, @doc.comments.build]) do |f| %>


	<p>
		<%= f.label :comment %><br>
		<%= f.text_area :comment %>
	</p>
	<br />
	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/docs/_form.html.haml
=simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit

app/views/docs/edit.html.haml
%h1 Edit Note

=render 'form'

app/views/docs/index.html.haml
- @doc.each do |doc|
  %h1= link_to doc.title, doc
  %p= doc.content
%button=link_to "New Note", new_doc_path
%button= link_to 'Logout', destroy_user_session_path, :method => :delete

app/views/docs/new.html.haml
%h1 New Note

= render 'form'

app/views/docs/show.html.erb
<h1><%= @doc.title %></h1>
<p><%= @doc.content %></p>

	<div id = "comments">
		<h2>
			<%= pluralize(@doc.comments.count, "Comment") %>
		</h2>
		<%= render @doc.comments %>
	</div>

	<h3>Join The Discussion</h3>
	<%= render 'comments/form' %>

<button><%= link_to "Delete Note", doc_path(@doc), method: :delete, data: {confirm: "Are you sure?"} %>
<button><%=link_to "Edit Note", edit_doc_path %></button>
<button><%=link_to "All Notes", docs_path %></button>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: 'logout' %>        
          </li>
          <li>
            <%= link_to "My Documents", docs_path, class: 'my-docs' %>
          </li>
          <li>
            <%= link_to "New Note", new_doc_path, class: 'new-note' %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Login', new_user_session_path, class: 'login'  %>  
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notebook</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render "layouts/nav" %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% unless current_page?(root_path) %>
  <div class = "container">
<% end %>
	<%= yield %>
<% unless current_page?(root_path) %>
	</div>
<% end %>

</body>
</html>

app/views/welcome/index.html.erb
<div class = "jumbotron welcome">
	<h1 class = "banner">
		Notosaurus
	</h1>
	<p>The T-Rex of Text</p>
	<% if user_signed_in? %>
		<button><%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: 'logout' %></button>
	<% else %>
		<button><%= link_to "Login", new_user_session_path %></button>
	<% end %>
</div>

<% if user_signed_in? && current_user.docs.count != 0 %>
<div class ="jumbotron recent-notes">
	<div class = "container">
		<h2 style = "text-align: center;">Your Most Recent Noto</h2>
		<hr />
		<center>
			<h3><%= link_to(@doc.title, @doc) %></h3>
			<p><%= truncate(@doc.content, length: 20) %></p>
		</center>
	</div>
</div>
<% end %>